# Generated by Django 4.1.3 on 2024-05-14 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blog_downvotes_blog_upvotes_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replies',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='replies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.replies'),
        ),
    ]
