# Generated by Django 4.1.3 on 2024-05-14 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='replies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.replies'),
        ),
        migrations.AlterField(
            model_name='replies',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
