# Generated by Django 4.1.3 on 2024-06-11 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='replies',
        ),
        migrations.AddField(
            model_name='replies',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.blog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10),
        ),
    ]
